AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Reddit serial compiler
Resources:
    RedditSerialCompilerApiLambda:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Properties:
                        RestApiId:
                            Ref: RedditSerialCompiler
                        Path: /{proxy+}
                        Method: ANY
                    Type: Api
            CodeUri: ./
            #            init py is important
            Handler: app.main.handler
            Runtime: python3.7
            Timeout: 300 # timeout of your lambda function
            MemorySize: 128 # memory size of your lambda function
            Description: The API for the reddit serial compiler
    RedditSerialCompiler:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            OpenApiVersion: '3.0.0'
